export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

export const ADD_ISSUEORCOMMENT_REQUEST = "ADD_ISSUEORCOMMENT_REQUEST";
export const ADD_ISSUEORCOMMENT_SUCCESS = "ADD_ISSUEORCOMMENT_SUCCESS";
export const ADD_ISSUEORCOMMENT_FAILURE = "ADD_ISSUEORCOMMENT_FAILURE";

export const UPDATE_ISSUEORCOMMENT_REQUEST = "UPDATE_ISSUEORCOMMENT_REQUEST";
export const UPDATE_ISSUEORCOMMENT_SUCCESS = "UPDATE_ISSUEORCOMMENT_SUCCESS";
export const UPDATE_ISSUEORCOMMENT_FAILURE = "UPDATE_ISSUEORCOMMENT_FAILURE";

export const DELETE_ISSUEORCOMMENT_REQUEST = "DELETE_ISSUEORCOMMENT_REQUEST";
export const DELETE_ISSUEORCOMMENT_SUCCESS = "DELETE_ISSUEORCOMMENT_SUCCESS";
export const DELETE_ISSUEORCOMMENT_FAILURE = "DELETE_ISSUEORCOMMENT_FAILURE";

export const DatabaseFileType = {
  prospectsFile: "prospectsFile",
  aiTrainingDataFile: "aiTrainingDataFile",
};
